### ISSUE TITLE
[help wanted] possible do a video tutorial how to use this file?

### ISSUE THREAD

**Issue by shiroamada** [galens/playback-gpx#1]
Is it possible do a video tutorial how to use this file?
I want to simulate a gps routing by using genymotion in waze.

Thanks!

**Comment by galens** [comment]
Hello,

Maybe at some point in the future I might be able to make a video of this, but as of now I don't have the time.  I can try to explain how to use it though.  You must have both python and genymotion installed on the machine you intend to use this on.

You must then obtain the internal ip address that genymotion gives the running emulated android instance.  You must also have a gpx file of your choosing, or you can use one that I provided.

After starting up genymotion, running an android emulation, obtaining the ip address and gpx file, you have all you need.  Simply run the python script, pass the correct arguments and it will broadcast the gpx coordinates to genymotion, thus simulating the positioning.

Hope this helps.
